// Generated by gencpp from file self_defined_msgs/face_msgs.msg
// DO NOT EDIT!


#ifndef SELF_DEFINED_MSGS_MESSAGE_FACE_MSGS_H
#define SELF_DEFINED_MSGS_MESSAGE_FACE_MSGS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <self_defined_msgs/my_list.h>

namespace self_defined_msgs
{
template <class ContainerAllocator>
struct face_msgs_
{
  typedef face_msgs_<ContainerAllocator> Type;

  face_msgs_()
    : location()  {
    }
  face_msgs_(const ContainerAllocator& _alloc)
    : location(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::self_defined_msgs::my_list_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::self_defined_msgs::my_list_<ContainerAllocator> >::other >  _location_type;
  _location_type location;



  enum {
    index = 0,
  };


  typedef boost::shared_ptr< ::self_defined_msgs::face_msgs_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::self_defined_msgs::face_msgs_<ContainerAllocator> const> ConstPtr;

}; // struct face_msgs_

typedef ::self_defined_msgs::face_msgs_<std::allocator<void> > face_msgs;

typedef boost::shared_ptr< ::self_defined_msgs::face_msgs > face_msgsPtr;
typedef boost::shared_ptr< ::self_defined_msgs::face_msgs const> face_msgsConstPtr;

// constants requiring out of line definition

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::self_defined_msgs::face_msgs_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::self_defined_msgs::face_msgs_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace self_defined_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'self_defined_msgs': ['/home/beta/Desktop/face_detect_ws/src/self_defined_msgs/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::self_defined_msgs::face_msgs_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::self_defined_msgs::face_msgs_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::self_defined_msgs::face_msgs_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::self_defined_msgs::face_msgs_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::self_defined_msgs::face_msgs_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::self_defined_msgs::face_msgs_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::self_defined_msgs::face_msgs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bee29f659ddcd80e70bd0b7494b2547b";
  }

  static const char* value(const ::self_defined_msgs::face_msgs_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbee29f659ddcd80eULL;
  static const uint64_t static_value2 = 0x70bd0b7494b2547bULL;
};

template<class ContainerAllocator>
struct DataType< ::self_defined_msgs::face_msgs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "self_defined_msgs/face_msgs";
  }

  static const char* value(const ::self_defined_msgs::face_msgs_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::self_defined_msgs::face_msgs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 index=0\n"
"my_list[] location\n"
"\n"
"================================================================================\n"
"MSG: self_defined_msgs/my_list\n"
"#list 4D\n"
"uint16 a=0\n"
"uint16 b=0\n"
"uint16 c=0\n"
"uint16 d=0\n"
;
  }

  static const char* value(const ::self_defined_msgs::face_msgs_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::self_defined_msgs::face_msgs_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.location);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct face_msgs_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::self_defined_msgs::face_msgs_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::self_defined_msgs::face_msgs_<ContainerAllocator>& v)
  {
    s << indent << "location[]" << std::endl;
    for (size_t i = 0; i < v.location.size(); ++i)
    {
      s << indent << "  location[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::self_defined_msgs::my_list_<ContainerAllocator> >::stream(s, indent + "    ", v.location[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SELF_DEFINED_MSGS_MESSAGE_FACE_MSGS_H
