// Generated by gencpp from file self_defined_msgs/my_list.msg
// DO NOT EDIT!


#ifndef SELF_DEFINED_MSGS_MESSAGE_MY_LIST_H
#define SELF_DEFINED_MSGS_MESSAGE_MY_LIST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace self_defined_msgs
{
template <class ContainerAllocator>
struct my_list_
{
  typedef my_list_<ContainerAllocator> Type;

  my_list_()
    {
    }
  my_list_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }





  enum {
    a = 0u,
    b = 0u,
    c = 0u,
    d = 0u,
  };


  typedef boost::shared_ptr< ::self_defined_msgs::my_list_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::self_defined_msgs::my_list_<ContainerAllocator> const> ConstPtr;

}; // struct my_list_

typedef ::self_defined_msgs::my_list_<std::allocator<void> > my_list;

typedef boost::shared_ptr< ::self_defined_msgs::my_list > my_listPtr;
typedef boost::shared_ptr< ::self_defined_msgs::my_list const> my_listConstPtr;

// constants requiring out of line definition

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::self_defined_msgs::my_list_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::self_defined_msgs::my_list_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace self_defined_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'self_defined_msgs': ['/home/beta/Desktop/face_detect_ws/src/self_defined_msgs/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::self_defined_msgs::my_list_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::self_defined_msgs::my_list_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::self_defined_msgs::my_list_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::self_defined_msgs::my_list_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::self_defined_msgs::my_list_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::self_defined_msgs::my_list_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::self_defined_msgs::my_list_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1d20127be13903cadd3a4c222505203d";
  }

  static const char* value(const ::self_defined_msgs::my_list_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1d20127be13903caULL;
  static const uint64_t static_value2 = 0xdd3a4c222505203dULL;
};

template<class ContainerAllocator>
struct DataType< ::self_defined_msgs::my_list_<ContainerAllocator> >
{
  static const char* value()
  {
    return "self_defined_msgs/my_list";
  }

  static const char* value(const ::self_defined_msgs::my_list_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::self_defined_msgs::my_list_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#list 4D\n"
"uint16 a=0\n"
"uint16 b=0\n"
"uint16 c=0\n"
"uint16 d=0\n"
;
  }

  static const char* value(const ::self_defined_msgs::my_list_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::self_defined_msgs::my_list_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct my_list_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::self_defined_msgs::my_list_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::self_defined_msgs::my_list_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // SELF_DEFINED_MSGS_MESSAGE_MY_LIST_H
