// Generated by gencpp from file face_detector/EnableSignal.msg
// DO NOT EDIT!


#ifndef FACE_DETECTOR_MESSAGE_ENABLESIGNAL_H
#define FACE_DETECTOR_MESSAGE_ENABLESIGNAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace face_detector
{
template <class ContainerAllocator>
struct EnableSignal_
{
  typedef EnableSignal_<ContainerAllocator> Type;

  EnableSignal_()
    : enable(0)  {
    }
  EnableSignal_(const ContainerAllocator& _alloc)
    : enable(0)  {
  (void)_alloc;
    }



   typedef uint8_t _enable_type;
  _enable_type enable;





  typedef boost::shared_ptr< ::face_detector::EnableSignal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::face_detector::EnableSignal_<ContainerAllocator> const> ConstPtr;

}; // struct EnableSignal_

typedef ::face_detector::EnableSignal_<std::allocator<void> > EnableSignal;

typedef boost::shared_ptr< ::face_detector::EnableSignal > EnableSignalPtr;
typedef boost::shared_ptr< ::face_detector::EnableSignal const> EnableSignalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::face_detector::EnableSignal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::face_detector::EnableSignal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace face_detector

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'face_detector': ['/home/beta/Desktop/face_detect_ws/src/face_detector/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::face_detector::EnableSignal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::face_detector::EnableSignal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::face_detector::EnableSignal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::face_detector::EnableSignal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::face_detector::EnableSignal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::face_detector::EnableSignal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::face_detector::EnableSignal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "34abd7794638063ef7576ad13e0da876";
  }

  static const char* value(const ::face_detector::EnableSignal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x34abd7794638063eULL;
  static const uint64_t static_value2 = 0xf7576ad13e0da876ULL;
};

template<class ContainerAllocator>
struct DataType< ::face_detector::EnableSignal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "face_detector/EnableSignal";
  }

  static const char* value(const ::face_detector::EnableSignal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::face_detector::EnableSignal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 enable\n"
;
  }

  static const char* value(const ::face_detector::EnableSignal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::face_detector::EnableSignal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.enable);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EnableSignal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::face_detector::EnableSignal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::face_detector::EnableSignal_<ContainerAllocator>& v)
  {
    s << indent << "enable: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.enable);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FACE_DETECTOR_MESSAGE_ENABLESIGNAL_H
